# Generated by Django 5.1.6 on 2025-02-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFWAP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdatafield',
            name='type',
            field=models.CharField(choices=[('String', 'String'), ('Number', 'Number'), ('Boolean', 'Boolean'), ('List', 'List'), ('Object', 'Object')], max_length=10),
        ),
    ]
