# Generated by Django 5.1.6 on 2025-02-14 05:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFWAP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TargetApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APP_name', models.CharField(max_length=20, unique=True)),
                ('APP_url', models.CharField(max_length=200, validators=[django.core.validators.URLValidator()])),
                ('user_behavior_cycle', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('SFWAP_address', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}:\\d{1,5}$')])),
                ('description', models.CharField(max_length=2048)),
                ('login_credentials', models.ManyToManyField(to='SFWAP.logincredential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
