# Generated by Django 5.1.6 on 2025-03-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFWAP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='role_list',
            field=models.JSONField(default=list),
        ),
    ]
