# Generated by Django 5.1.6 on 2025-02-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFWAP', '0002_alter_requestdatafield_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetapplication',
            name='detect_state',
            field=models.CharField(choices=[('BASIC_INFO_TO_CONFIGURE', 'BASIC_INFO_TO_CONFIGURE'), ('API_LIST_TO_DISCOVER', 'API_LIST_TO_DISCOVER'), ('API_LIST_TO_IMPROVE', 'API_LIST_TO_IMPROVE'), ('MODEL_FEATURES_TO_CONFIGURE', 'MODEL_FEATURES_TO_CONFIGURE'), ('STARTED', 'STARTED'), ('PAUSED', 'PAUSED')], max_length=50),
        ),
    ]
