# Generated by Django 5.1.6 on 2025-03-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFWAP', '0002_api_role_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='role_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
