# Generated by Django 5.1.6 on 2025-02-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFWAP', '0003_targetapplication_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetapplication',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
