# Generated by Django 5.1.6 on 2025-02-14 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFWAP', '0004_targetapplication_is_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_url', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.URLValidator()])),
                ('sample_request_data', models.CharField(blank=True, max_length=200, null=True)),
                ('request_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10)),
                ('function_description', models.CharField(max_length=200)),
                ('permission_info', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='PathSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_path_variable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestDataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('String', 'String'), ('Number', 'Number'), ('List', 'List'), ('Object', 'Object')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RequestParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_necessary', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='targetapplication',
            name='last_API_discovery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetapplication',
            name='last_model_construction_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetapplication',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AddField(
            model_name='targetapplication',
            name='discovered_API_list',
            field=models.ManyToManyField(related_name='discovered_in_apps', to='SFWAP.api'),
        ),
        migrations.AddField(
            model_name='targetapplication',
            name='user_API_list',
            field=models.ManyToManyField(related_name='used_in_apps', to='SFWAP.api'),
        ),
        migrations.AddField(
            model_name='api',
            name='path_segment_list',
            field=models.ManyToManyField(to='SFWAP.pathsegment'),
        ),
        migrations.AddField(
            model_name='api',
            name='request_data_fields',
            field=models.ManyToManyField(to='SFWAP.requestdatafield'),
        ),
        migrations.AddField(
            model_name='api',
            name='request_param_list',
            field=models.ManyToManyField(to='SFWAP.requestparam'),
        ),
    ]
